version: '3'
services: 
    db:
        image: 'postgres:12.3'
        volumes: 
            - postgres:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: postgres

    redis:
        image: 'redis:6.0.5'
        command: redis-server
        ports: 
            - '6379:6379'
        volumes: 
            - redis:/var/lib/redis/data

    jobs:
        depends_on: 
            - db
            - redis
            - website
        build: .
        command: bash start_jobs.sh
        volumes: 
            - .:/cornell-notebook
            - gems:/gems

    mailcatcher:
        image: yappabe/mailcatcher
        ports: 
            - 1025:1025
            - 1080:1080

    website:
        tty: true
        stdin_open: true
        depends_on: 
            - db
            - redis
        environment: 
            DB_PASSWORD: postgres
        build: .
        command: bash start.sh
        ports: 
            - 3000:3000
        volumes: 
            - .:/cornell-notebook
            - gems:/gems

volumes: 
    postgres:
    gems:
    redis: